drop TABLE STUDENT;

CREATE TABLE STUDENT
(
roll_no number(4) PRIMARY KEY,
name varchar2(50) NOT NULL,
marks number(3),
grade char(1),
course_id number(4)
);


CREATE TRIGGER TR_GRADE
BEFORE UPDATE OR INSERT ON STUDENT
FOR EACH ROW
BEGIN
IF :NEW.MARKS>80 THEN
:NEW.GRADE:='A';
ELSIF :NEW.MARKS>=70 AND :NEW.MARKS<80 THEN
:NEW.GRADE:='B';
ELSIF :NEW.MARKS>=60 AND :NEW.MARKS<70 THEN
:NEW.GRADE:='C';
ELSIF :NEW.MARKS>50 AND :NEW.MARKS<60 THEN
:NEW.GRADE:='D';
ELSIF :NEW.MARKS>40 AND :NEW.MARKS<50 THEN
:NEW.GRADE:='E';
ELSIF :NEW.MARKS<=40 THEN
:NEW.GRADE:='F';
END IF;
END TR_GRADE;
/
insert into STUDENT VALUES (1,'SATHISH',3,NULL,123);
insert into STUDENT values(7,'rabiul',10,NULL,123);
	insert into STUDENT values(8,'rabil',60,NULL,123);
SELECT * FROM STUDENT;

DROP TABLE test;
CREATE TABLE test (
Roll int,
Name Varchar (10)
);
INSERT INTO test VALUES (1, 'A');
INSERT INTO test VALUES (2, 'B');
INSERT INTO test VALUES (3, 'C');
INSERT INTO test VALUES (4, 'D');
INSERT INTO test VALUES (5, 'E');
COMMIT;
SELECT * FROM test;


DROP TABLE test2;
CREATE TABLE test2 (
Continent_ID int,
Continent_Name varchar(20)
);
INSERT INTO test2 VALUES (1, 'Asia');
INSERT INTO test2 VALUES (2, 'Europe');
INSERT INTO test2 VALUES (3, 'Australia');
INSERT INTO test2 VALUES (4, 'North America');
INSERT INTO test2 VALUES (5, 'South America');
commit;